export const INFURA_GATEWAY: string = "https://thedial.infura-ipfs.io";
export const GROVE_GATEWAY: string = "https://api.grove.storage/";

export const IPFS_REGEX: RegExp = /\b(Qm[1-9A-Za-z]{44}|ba[A-Za-z2-7]{57})\b/;
export const LUCIDITY_WORKFLOWS_CONTRACT: `0x${string}` =
  "0xfc9aEAC38c1169028fcbd3d4A91e8A0103606b70";

export const SET_UP: string[] = [
  "Windows",
  "macOS",
  "Intel",
  "AMD",
  "Apple Silicon",
  "RTX 4090",
  "RTX 4080",
  "RX 7900 XTX",
  "NVIDIA",
];

export const ASSISTANT_ID: string = "asst_LuecDFnqperlOUDKxwK25YVM";

export const SUGGESTED_TAGS: string[] = [
  "cyberpunk",
  "vaporwave",
  "cottagecore",
  "gothcore",
  "dark academia",
  "light academia",
  "steampunk",
  "solarpunk",
  "afrofuturism",
  "baroque",
  "art nouveau",
  "impressionism",
  "expressionism",
  "surrealism",
  "minimalism",
  "maximalism",
  "brutalism",
  "neoclassical",
  "streetwear",
  "techwear",
  "y2k",
  "normcore",
  "gothic",
  "lolita",
  "kawaii",
  "harajuku",
  "ethereal",
  "grunge",
  "fairycore",
  "dreamcore",
  "weirdcore",
  "depth map",
  "normal map",
  "displacement map",
  "sam2",
  "florence",
  "latent diffusion",
  "stable diffusion",
  "controlnet",
  "hypernetwork",
  "lora",
  "inpainting",
  "outpainting",
  "img2img",
  "upscale",

  "neon",
  "glitch art",
  "holographic",
  "synthwave",
  "retrowave",
  "pixel art",
  "low poly",
  "isometric",
  "cinematic",
  "ambient occlusion",
  "bokeh",
  "tilt-shift",
  "chiaroscuro",
  "duotone",
  "anaglyph",
  "marble",
  "iridescent",
  "liquid metal",
  "rust",
  "patina",
  "metallic",
  "glass",
  "frosted",
  "crystalline",
  "geode",
  "watercolor",
  "ink wash",
  "gouache",
];
